// Country name → ISO 3166-1 alpha-2 code.
// Includes ICAO formal names (inferred from ICAO 24-bit address allocation).
export const COUNTRY_CODE = {
  // A
  'Afghanistan':'AF','Islamic Republic of Afghanistan':'AF',
  'Albania':'AL','Republic of Albania':'AL',
  'Algeria':'DZ','People\'s Democratic Republic of Algeria':'DZ','Democratic and Popular Republic of Algeria':'DZ',
  'Angola':'AO','Republic of Angola':'AO',
  'Argentina':'AR','Argentine Republic':'AR',
  'Armenia':'AM','Republic of Armenia':'AM',
  'Australia':'AU','Commonwealth of Australia':'AU',
  'Austria':'AT','Republic of Austria':'AT',
  'Azerbaijan':'AZ','Republic of Azerbaijan':'AZ',
  // B
  'Bahrain':'BH','Kingdom of Bahrain':'BH','Bahrain, Kingdom of':'BH',
  'Bangladesh':'BD','People\'s Republic of Bangladesh':'BD',
  'Belarus':'BY','Republic of Belarus':'BY',
  'Belgium':'BE','Kingdom of Belgium':'BE',
  'Bolivia':'BO','Bolivia, Plurinational State of':'BO','Plurinational State of Bolivia':'BO',
  'Bosnia and Herzegovina':'BA',
  'Botswana':'BW','Republic of Botswana':'BW',
  'Brazil':'BR','Federative Republic of Brazil':'BR',
  'Brunei Darussalam':'BN','Brunei':'BN','Nation of Brunei':'BN',
  'Bulgaria':'BG','Republic of Bulgaria':'BG',
  'Burkina Faso':'BF',
  'Burundi':'BI','Republic of Burundi':'BI',
  // C
  'Cambodia':'KH',
  'Canada':'CA',
  'Chile':'CL',
  'China':'CN','People\'s Republic of China':'CN',
  'Colombia':'CO','Republic of Colombia':'CO',
  'Congo, Democratic Republic of the':'CD','Democratic Republic of the Congo':'CD','DR Congo':'CD',
  'Congo':'CG','Republic of the Congo':'CG',
  'Croatia':'HR','Republic of Croatia':'HR',
  'Cuba':'CU','Republic of Cuba':'CU',
  'Cyprus':'CY','Republic of Cyprus':'CY',
  'Czech Republic':'CZ','Czechia':'CZ',
  // D
  'Denmark':'DK',
  'Djibouti':'DJ','Republic of Djibouti':'DJ',
  // E
  'Ecuador':'EC',
  'Egypt':'EG','Arab Republic of Egypt':'EG',
  'Eritrea':'ER','State of Eritrea':'ER',
  'Estonia':'EE','Republic of Estonia':'EE',
  'Ethiopia':'ET','Federal Democratic Republic of Ethiopia':'ET',
  // F
  'Finland':'FI','Republic of Finland':'FI',
  'France':'FR','French Republic':'FR',
  // G
  'Georgia':'GE','Republic of Georgia':'GE',
  'Germany':'DE','Federal Republic of Germany':'DE',
  'Ghana':'GH','Republic of Ghana':'GH',
  'Greece':'GR','Hellenic Republic':'GR',
  // H
  'Hungary':'HU',
  // I
  'India':'IN','Republic of India':'IN',
  'Indonesia':'ID','Republic of Indonesia':'ID',
  'Iran':'IR','Iran, Islamic Republic of':'IR','Islamic Republic of Iran':'IR',
  'Iraq':'IQ','Republic of Iraq':'IQ',
  'Ireland':'IE','Republic of Ireland':'IE',
  'Israel':'IL','State of Israel':'IL',
  'Italy':'IT','Italian Republic':'IT',
  // J
  'Japan':'JP',
  'Jordan':'JO','Hashemite Kingdom of Jordan':'JO','Jordan, Hashemite Kingdom of':'JO',
  // K
  'Kazakhstan':'KZ','Republic of Kazakhstan':'KZ',
  'Kenya':'KE','Republic of Kenya':'KE',
  'Korea, Democratic People\'s Republic of':'KP','North Korea':'KP','Democratic People\'s Republic of Korea':'KP',
  'Korea, Republic of':'KR','South Korea':'KR','Republic of Korea':'KR',
  'Kuwait':'KW','State of Kuwait':'KW',
  'Kyrgyzstan':'KG','Kyrgyz Republic':'KG',
  // L
  'Lao People\'s Democratic Republic':'LA','Laos':'LA',
  'Latvia':'LV','Republic of Latvia':'LV',
  'Lebanon':'LB','Lebanese Republic':'LB','Republic of Lebanon':'LB',
  'Libya':'LY','Libyan Arab Jamahiriya':'LY','State of Libya':'LY',
  'Lithuania':'LT','Republic of Lithuania':'LT',
  'Luxembourg':'LU',
  // M
  'Malaysia':'MY',
  'Maldives':'MV','Republic of Maldives':'MV',
  'Malta':'MT','Republic of Malta':'MT',
  'Mauritania':'MR','Islamic Republic of Mauritania':'MR',
  'Mexico':'MX','United Mexican States':'MX',
  'Moldova':'MD','Moldova, Republic of':'MD','Republic of Moldova':'MD',
  'Mongolia':'MN',
  'Montenegro':'ME','Republic of Montenegro':'ME',
  'Morocco':'MA','Kingdom of Morocco':'MA',
  'Mozambique':'MZ','Republic of Mozambique':'MZ',
  'Myanmar':'MM','Republic of the Union of Myanmar':'MM',
  // N
  'Namibia':'NA','Republic of Namibia':'NA',
  'Nepal':'NP','Federal Democratic Republic of Nepal':'NP',
  'Netherlands':'NL','Kingdom of the Netherlands':'NL',
  'New Zealand':'NZ',
  'Nigeria':'NG','Federal Republic of Nigeria':'NG',
  'North Macedonia':'MK','Republic of North Macedonia':'MK','Macedonia':'MK',
  'Norway':'NO','Kingdom of Norway':'NO',
  // O
  'Oman':'OM','Sultanate of Oman':'OM',
  // P
  'Pakistan':'PK','Islamic Republic of Pakistan':'PK',
  'Palestine':'PS','Palestinian Authority':'PS','State of Palestine':'PS','Palestinian Territory':'PS',
  'Peru':'PE','Republic of Peru':'PE',
  'Philippines':'PH','Republic of the Philippines':'PH',
  'Poland':'PL','Republic of Poland':'PL',
  'Portugal':'PT','Portuguese Republic':'PT',
  // Q
  'Qatar':'QA','State of Qatar':'QA',
  // R
  'Romania':'RO','Republic of Romania':'RO',
  'Russia':'RU','Russian Federation':'RU',
  'Rwanda':'RW','Republic of Rwanda':'RW',
  // S
  'San Marino':'SM','Republic of San Marino':'SM',
  'Saudi Arabia':'SA','Kingdom of Saudi Arabia':'SA',
  'Senegal':'SN','Republic of Senegal':'SN',
  'Serbia':'RS','Republic of Serbia':'RS',
  'Singapore':'SG','Republic of Singapore':'SG',
  'Slovakia':'SK','Slovak Republic':'SK',
  'Slovenia':'SI','Republic of Slovenia':'SI',
  'Somalia':'SO','Federal Republic of Somalia':'SO',
  'South Africa':'ZA','Republic of South Africa':'ZA',
  'South Sudan':'SS','Republic of South Sudan':'SS',
  'Spain':'ES','Kingdom of Spain':'ES',
  'Sri Lanka':'LK','Democratic Socialist Republic of Sri Lanka':'LK',
  'Sudan':'SD','Republic of the Sudan':'SD','Republic of Sudan':'SD',
  'Sweden':'SE','Kingdom of Sweden':'SE',
  'Switzerland':'CH','Swiss Confederation':'CH',
  'Syria':'SY','Syrian Arab Republic':'SY',
  // T
  'Taiwan':'TW','Taiwan, Province of China':'TW',
  'Tajikistan':'TJ','Republic of Tajikistan':'TJ',
  'Tanzania':'TZ','Tanzania, United Republic of':'TZ','United Republic of Tanzania':'TZ',
  'Thailand':'TH','Kingdom of Thailand':'TH',
  'Tunisia':'TN','Republic of Tunisia':'TN','Tunisian Republic':'TN',
  'Turkey':'TR','Türkiye':'TR','Republic of Turkey':'TR','Republic of Türkiye':'TR',
  'Turkmenistan':'TM',
  // U
  'Uganda':'UG','Republic of Uganda':'UG',
  'Ukraine':'UA',
  'United Arab Emirates':'AE',
  'United Kingdom':'GB','United Kingdom of Great Britain and Northern Ireland':'GB',
  'United States':'US','United States of America':'US',
  'Uzbekistan':'UZ','Republic of Uzbekistan':'UZ',
  // V
  'Venezuela':'VE','Venezuela, Bolivarian Republic of':'VE','Bolivarian Republic of Venezuela':'VE',
  'Viet Nam':'VN','Vietnam':'VN','Socialist Republic of Viet Nam':'VN',
  // Y
  'Yemen':'YE','Republic of Yemen':'YE',
  // Z
  'Zambia':'ZM','Republic of Zambia':'ZM',
  'Zimbabwe':'ZW','Republic of Zimbabwe':'ZW',
}
